#! /bin/bash

# Disables XFCE compositor to improve framerate
xfconf-query -c xfwm4 -p /general/use_compositing -s false

# Turns off the output from the left and right monitor in order to ensure Nvidia GSync can run.
# Run 'xrandr' to see which monitors are connected and which portion of the screen they render.
xrandr --output HDMI-0 --off
xrandr --output DP-0 --off

# Sets eth NIC to 100Mb/s full duplex
sudo ethtool -s enp4s0 speed 100 duplex full autoneg on

# Toggle GSync off
nvidia-settings -a AllowVRR=0
nvidia-settings -a ShowVRRVisualIndicator=0

# Flip the bit for needed caps
sudo setcap cap_sys_admin+p $(readlink -f $(which sunshine))
